# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Content.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Content(object):
    def setupUi(self, Content):
        Content.setObjectName("Content")
        Content.resize(277, 468)
        Content.setStyleSheet("")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Content)
        self.verticalLayout_4.setContentsMargins(10, 5, 10, 5)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_3 = QtWidgets.QWidget(Content)
        self.widget_3.setStyleSheet("\n"
"QWidget#widget_3{border-image: url(:/img/img/v2-59b514faac600379b83906e0baabf7a6_720w.jpg);}")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setStyleSheet("background-color: rgba(131, 175, 155, 220)")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_7.setContentsMargins(5, 20, 5, 20)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setStyleSheet("font: 87 14pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_19 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_19.setStyleSheet("font: 75 10pt \"微软雅黑\";\n"
"color:rgb(236, 236, 236)")
        self.pushButton_19.setFlat(True)
        self.pushButton_19.setObjectName("pushButton_19")
        self.verticalLayout_9.addWidget(self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_20.setStyleSheet("font: 75 10pt \"微软雅黑\";\n"
"color:rgb(236, 236, 236)")
        self.pushButton_20.setFlat(True)
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout_9.addWidget(self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_21.setStyleSheet("font: 75 10pt \"微软雅黑\";\n"
"color:rgb(236, 236, 236)")
        self.pushButton_21.setFlat(True)
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_9.addWidget(self.pushButton_21)
        self.pushButton_22 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_22.setStyleSheet("font: 75 10pt \"微软雅黑\";\n"
"color:rgb(236, 236, 236)")
        self.pushButton_22.setFlat(True)
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalLayout_9.addWidget(self.pushButton_22)
        self.pushButton_23 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_23.setStyleSheet("font: 75 10pt \"微软雅黑\";\n"
"color:rgb(236, 236, 236)")
        self.pushButton_23.setFlat(True)
        self.pushButton_23.setObjectName("pushButton_23")
        self.verticalLayout_9.addWidget(self.pushButton_23)
        self.pushButton_24 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_24.setStyleSheet("font: 75 10pt \"微软雅黑\";\n"
"color:rgb(236, 236, 236)")
        self.pushButton_24.setCheckable(False)
        self.pushButton_24.setAutoDefault(False)
        self.pushButton_24.setDefault(False)
        self.pushButton_24.setFlat(True)
        self.pushButton_24.setObjectName("pushButton_24")
        self.verticalLayout_9.addWidget(self.pushButton_24)
        self.pushButton_25 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_25.setStyleSheet("font: 75 10pt \"微软雅黑\";\n"
"color:rgb(236, 236, 236)")
        self.pushButton_25.setFlat(True)
        self.pushButton_25.setObjectName("pushButton_25")
        self.verticalLayout_9.addWidget(self.pushButton_25)
        self.pushButton_26 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_26.setStyleSheet("font: 75 10pt \"微软雅黑\";\n"
"color:rgb(236, 236, 236)")
        self.pushButton_26.setFlat(True)
        self.pushButton_26.setObjectName("pushButton_26")
        self.verticalLayout_9.addWidget(self.pushButton_26)
        self.pushButton_27 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_27.setStyleSheet("font: 75 10pt \"微软雅黑\";\n"
"color:rgb(236, 236, 236)")
        self.pushButton_27.setFlat(True)
        self.pushButton_27.setObjectName("pushButton_27")
        self.verticalLayout_9.addWidget(self.pushButton_27)
        self.verticalLayout_8.addLayout(self.verticalLayout_9)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 5)
        self.verticalLayout_8.setStretch(2, 5)
        self.verticalLayout_8.setStretch(3, 6)
        self.verticalLayout_7.addLayout(self.verticalLayout_8)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"font: 75 10pt \"微软雅黑\";\n"
"color:rgb(236, 236, 236);\n"
"min-width: 70px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/back.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_7.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_6.addWidget(self.widget_2)
        self.verticalLayout_5.addWidget(self.widget)
        self.verticalLayout_4.addWidget(self.widget_3)

        self.retranslateUi(Content)
        QtCore.QMetaObject.connectSlotsByName(Content)

    def retranslateUi(self, Content):
        _translate = QtCore.QCoreApplication.translate
        Content.setWindowTitle(_translate("Content", "Form"))
        self.label_2.setText(_translate("Content", "Zhku"))
        self.pushButton_19.setText(_translate("Content", "学生学籍"))
        self.pushButton_20.setText(_translate("Content", "培养方案"))
        self.pushButton_21.setText(_translate("Content", "网上选课"))
        self.pushButton_22.setText(_translate("Content", "教学安排"))
        self.pushButton_23.setText(_translate("Content", "考试安排"))
        self.pushButton_24.setText(_translate("Content", "学生成绩"))
        self.pushButton_25.setText(_translate("Content", "教材信息"))
        self.pushButton_26.setText(_translate("Content", "网上评教"))
        self.pushButton_27.setText(_translate("Content", "个人信息"))
        self.pushButton_3.setText(_translate("Content", "注销"))
import qr_img_rc
