# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ScoreTableWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(935, 600)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 10, 0, 10)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_2 = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("font: 75 9pt \"微软雅黑\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox {\n"
"    border:none;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"    \n"
"    image: url(:/img/img/arrows_down_double-34.svg);\n"
"}\n"
"\n"
"")
        self.comboBox.setEditable(False)
        self.comboBox.setCurrentText("")
        self.comboBox.setFrame(False)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_6.addWidget(self.comboBox)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet("font: 75 9pt \"微软雅黑\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("QComboBox {\n"
"    border:none;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"    \n"
"    image: url(:/img/img/arrows_down_double-34.svg);\n"
"}\n"
"\n"
"")
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setFrame(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_6.addWidget(self.comboBox_2)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_6 = QtWidgets.QWidget(self.widget_4)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.radioButton = QtWidgets.QRadioButton(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton.sizePolicy().hasHeightForWidth())
        self.radioButton.setSizePolicy(sizePolicy)
        self.radioButton.setStyleSheet("QRadioButton{\n"
"    spacing: 2px;\n"
"    color: red;\n"
"}\n"
"QRadioButton::indicator {\n"
"\n"
"}\n"
"QRadioButton::indicator:unchecked {\n"
"    \n"
"    \n"
"    \n"
"    image: url(:/img/img/arrows_button_off.svg);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    \n"
"    \n"
"    image: url(:/img/img/arrows_button_on.svg);\n"
"}\n"
"url(:/img/img/arrows_button_on.svg)")
        self.radioButton.setChecked(True)
        self.radioButton.setAutoRepeat(False)
        self.radioButton.setAutoExclusive(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_10.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_2.sizePolicy().hasHeightForWidth())
        self.radioButton_2.setSizePolicy(sizePolicy)
        self.radioButton_2.setStyleSheet("QRadioButton{\n"
"    spacing: 2px;\n"
"    color: red;\n"
"}\n"
"QRadioButton::indicator {\n"
"\n"
"}\n"
"QRadioButton::indicator:unchecked {\n"
"    \n"
"    \n"
"    \n"
"    image: url(:/img/img/arrows_button_off.svg);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    \n"
"    \n"
"    image: url(:/img/img/arrows_button_on.svg);\n"
"}\n"
"url(:/img/img/arrows_button_on.svg)")
        self.radioButton_2.setAutoRepeat(False)
        self.radioButton_2.setAutoExclusive(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_10.addWidget(self.radioButton_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8.addWidget(self.widget_6)
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_3.setStyleSheet("QRadioButton{\n"
"    spacing: 2px;\n"
"    color: red;\n"
"}\n"
"QRadioButton::indicator {\n"
"\n"
"}\n"
"QRadioButton::indicator:unchecked {\n"
"    \n"
"    \n"
"    \n"
"    image: url(:/img/img/arrows_button_off.svg);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    \n"
"    \n"
"    image: url(:/img/img/arrows_button_on.svg);\n"
"}\n"
"url(:/img/img/arrows_button_on.svg)")
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setAutoExclusive(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_5.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_4.setStyleSheet("QRadioButton{\n"
"    spacing: 2px;\n"
"    color: red;\n"
"}\n"
"QRadioButton::indicator {\n"
"\n"
"}\n"
"QRadioButton::indicator:unchecked {\n"
"    \n"
"    \n"
"    \n"
"    image: url(:/img/img/arrows_button_off.svg);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    \n"
"    \n"
"    image: url(:/img/img/arrows_button_on.svg);\n"
"}\n"
"url(:/img/img/arrows_button_on.svg)")
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_5.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_5.setStyleSheet("QRadioButton{\n"
"    spacing: 2px;\n"
"    color: red;\n"
"}\n"
"QRadioButton::indicator {\n"
"\n"
"}\n"
"QRadioButton::indicator:unchecked {\n"
"    \n"
"    \n"
"    \n"
"    image: url(:/img/img/arrows_button_off.svg);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    \n"
"    \n"
"    image: url(:/img/img/arrows_button_on.svg);\n"
"}\n"
"url(:/img/img/arrows_button_on.svg)")
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_5.addWidget(self.radioButton_5)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8.addWidget(self.widget_3)
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.radioButton_6 = QtWidgets.QRadioButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_6.sizePolicy().hasHeightForWidth())
        self.radioButton_6.setSizePolicy(sizePolicy)
        self.radioButton_6.setStyleSheet("QRadioButton{\n"
"    spacing: 2px;\n"
"    color: red;\n"
"}\n"
"QRadioButton::indicator {\n"
"\n"
"}\n"
"QRadioButton::indicator:unchecked {\n"
"    \n"
"    \n"
"    \n"
"    image: url(:/img/img/arrows_button_off.svg);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    \n"
"    \n"
"    image: url(:/img/img/arrows_button_on.svg);\n"
"}\n"
"url(:/img/img/arrows_button_on.svg)")
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setAutoRepeat(False)
        self.radioButton_6.setAutoExclusive(True)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_7.addWidget(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_7.sizePolicy().hasHeightForWidth())
        self.radioButton_7.setSizePolicy(sizePolicy)
        self.radioButton_7.setStyleSheet("QRadioButton{\n"
"    spacing: 2px;\n"
"    color: red;\n"
"}\n"
"QRadioButton::indicator {\n"
"\n"
"}\n"
"QRadioButton::indicator:unchecked {\n"
"    \n"
"    \n"
"    \n"
"    image: url(:/img/img/arrows_button_off.svg);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    \n"
"    \n"
"    image: url(:/img/img/arrows_button_on.svg);\n"
"}\n"
"url(:/img/img/arrows_button_on.svg)")
        self.radioButton_7.setAutoRepeat(False)
        self.radioButton_7.setAutoExclusive(True)
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout_7.addWidget(self.radioButton_7)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addWidget(self.widget_5)
        self.horizontalLayout_6.addWidget(self.widget_4)
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4.addWidget(self.widget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "学年"))
        self.label_3.setText(_translate("Form", "学期"))
        self.radioButton.setText(_translate("Form", "原始成绩"))
        self.radioButton_2.setText(_translate("Form", "有效成绩"))
        self.radioButton_3.setText(_translate("Form", "入学以来"))
        self.radioButton_4.setText(_translate("Form", "学年"))
        self.radioButton_5.setText(_translate("Form", "学期"))
        self.radioButton_6.setText(_translate("Form", "主修"))
        self.radioButton_7.setText(_translate("Form", "辅修"))
        self.pushButton.setText(_translate("Form", "检索"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "查看成绩"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))
import qr_img_rc
