# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ZhkuMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ZhkuMainWindow(object):
    def setupUi(self, ZhkuMainWindow):
        ZhkuMainWindow.setObjectName("ZhkuMainWindow")
        ZhkuMainWindow.resize(1007, 543)
        ZhkuMainWindow.setStyleSheet("QMainWindow#ZhkuMainWindow{\n"
"border-image:url(:/img/img/ece414499b12f26fc1cdc8ccd7e019ea.jpg)}")
        self.centralwidget = QtWidgets.QWidget(ZhkuMainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2.addWidget(self.widget_2)
        ZhkuMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ZhkuMainWindow)
        QtCore.QMetaObject.connectSlotsByName(ZhkuMainWindow)

    def retranslateUi(self, ZhkuMainWindow):
        _translate = QtCore.QCoreApplication.translate
        ZhkuMainWindow.setWindowTitle(_translate("ZhkuMainWindow", "MainWindow"))
import qr_img_rc
